using System.Collections.Generic;
using Enfo.Domain.Entities;

namespace Enfo.Infrastructure.SeedData
{
    public static partial class ProdSeedData
    {
        public static County[] GetCounties()
        {
            var counties = new List<County> {
                new County { Id = 1, CountyName = "Appling" },
                new County { Id = 2, CountyName = "Atkinson" },
                new County { Id = 3, CountyName = "Bacon" },
                new County { Id = 4, CountyName = "Baker" },
                new County { Id = 5, CountyName = "Baldwin" },
                new County { Id = 6, CountyName = "Banks" },
                new County { Id = 7, CountyName = "Barrow" },
                new County { Id = 8, CountyName = "Bartow" },
                new County { Id = 9, CountyName = "Ben Hill" },
                new County { Id = 10, CountyName = "Berrien" },
                new County { Id = 11, CountyName = "Bibb" },
                new County { Id = 12, CountyName = "Bleckley" },
                new County { Id = 13, CountyName = "Brantley" },
                new County { Id = 14, CountyName = "Brooks" },
                new County { Id = 15, CountyName = "Bryan" },
                new County { Id = 16, CountyName = "Bulloch" },
                new County { Id = 17, CountyName = "Burke" },
                new County { Id = 18, CountyName = "Butts" },
                new County { Id = 19, CountyName = "Calhoun" },
                new County { Id = 20, CountyName = "Camden" },
                new County { Id = 21, CountyName = "Candler" },
                new County { Id = 22, CountyName = "Carroll" },
                new County { Id = 23, CountyName = "Catoosa" },
                new County { Id = 24, CountyName = "Charlton" },
                new County { Id = 25, CountyName = "Chatham" },
                new County { Id = 26, CountyName = "Chattahoochee" },
                new County { Id = 27, CountyName = "Chattooga" },
                new County { Id = 28, CountyName = "Cherokee" },
                new County { Id = 29, CountyName = "Clarke" },
                new County { Id = 30, CountyName = "Clay" },
                new County { Id = 31, CountyName = "Clayton" },
                new County { Id = 32, CountyName = "Clinch" },
                new County { Id = 33, CountyName = "Cobb" },
                new County { Id = 34, CountyName = "Coffee" },
                new County { Id = 35, CountyName = "Colquitt" },
                new County { Id = 36, CountyName = "Columbia" },
                new County { Id = 37, CountyName = "Cook" },
                new County { Id = 38, CountyName = "Coweta" },
                new County { Id = 39, CountyName = "Crawford" },
                new County { Id = 40, CountyName = "Crisp" },
                new County { Id = 41, CountyName = "Dade" },
                new County { Id = 42, CountyName = "Dawson" },
                new County { Id = 43, CountyName = "Decatur" },
                new County { Id = 44, CountyName = "DeKalb" },
                new County { Id = 45, CountyName = "Dodge" },
                new County { Id = 46, CountyName = "Dooly" },
                new County { Id = 47, CountyName = "Dougherty" },
                new County { Id = 48, CountyName = "Douglas" },
                new County { Id = 49, CountyName = "Early" },
                new County { Id = 50, CountyName = "Echols" },
                new County { Id = 51, CountyName = "Effingham" },
                new County { Id = 52, CountyName = "Elbert" },
                new County { Id = 53, CountyName = "Emanuel" },
                new County { Id = 54, CountyName = "Evans" },
                new County { Id = 55, CountyName = "Fannin" },
                new County { Id = 56, CountyName = "Fayette" },
                new County { Id = 57, CountyName = "Floyd" },
                new County { Id = 58, CountyName = "Forsyth" },
                new County { Id = 59, CountyName = "Franklin" },
                new County { Id = 60, CountyName = "Fulton" },
                new County { Id = 61, CountyName = "Gilmer" },
                new County { Id = 62, CountyName = "Glascock" },
                new County { Id = 63, CountyName = "Glynn" },
                new County { Id = 64, CountyName = "Gordon" },
                new County { Id = 65, CountyName = "Grady" },
                new County { Id = 66, CountyName = "Greene" },
                new County { Id = 67, CountyName = "Gwinnett" },
                new County { Id = 68, CountyName = "Habersham" },
                new County { Id = 69, CountyName = "Hall" },
                new County { Id = 70, CountyName = "Hancock" },
                new County { Id = 71, CountyName = "Haralson" },
                new County { Id = 72, CountyName = "Harris" },
                new County { Id = 73, CountyName = "Hart" },
                new County { Id = 74, CountyName = "Heard" },
                new County { Id = 75, CountyName = "Henry" },
                new County { Id = 76, CountyName = "Houston" },
                new County { Id = 77, CountyName = "Irwin" },
                new County { Id = 78, CountyName = "Jackson" },
                new County { Id = 79, CountyName = "Jasper" },
                new County { Id = 80, CountyName = "Jeff Davis" },
                new County { Id = 81, CountyName = "Jefferson" },
                new County { Id = 82, CountyName = "Jenkins" },
                new County { Id = 83, CountyName = "Johnson" },
                new County { Id = 84, CountyName = "Jones" },
                new County { Id = 85, CountyName = "Lamar" },
                new County { Id = 86, CountyName = "Lanier" },
                new County { Id = 87, CountyName = "Laurens" },
                new County { Id = 88, CountyName = "Lee" },
                new County { Id = 89, CountyName = "Liberty" },
                new County { Id = 90, CountyName = "Lincoln" },
                new County { Id = 91, CountyName = "Long" },
                new County { Id = 92, CountyName = "Lowndes" },
                new County { Id = 93, CountyName = "Lumpkin" },
                new County { Id = 94, CountyName = "Macon" },
                new County { Id = 95, CountyName = "Madison" },
                new County { Id = 96, CountyName = "Marion" },
                new County { Id = 97, CountyName = "McDuffie" },
                new County { Id = 98, CountyName = "McIntosh" },
                new County { Id = 99, CountyName = "Meriwether" },
                new County { Id = 100, CountyName = "Miller" },
                new County { Id = 101, CountyName = "Mitchell" },
                new County { Id = 102, CountyName = "Monroe" },
                new County { Id = 103, CountyName = "Montgomery" },
                new County { Id = 104, CountyName = "Morgan" },
                new County { Id = 105, CountyName = "Murray" },
                new County { Id = 106, CountyName = "Muscogee" },
                new County { Id = 107, CountyName = "Newton" },
                new County { Id = 108, CountyName = "Oconee" },
                new County { Id = 109, CountyName = "Oglethorpe" },
                new County { Id = 110, CountyName = "Paulding" },
                new County { Id = 111, CountyName = "Peach" },
                new County { Id = 112, CountyName = "Pickens" },
                new County { Id = 113, CountyName = "Pierce" },
                new County { Id = 114, CountyName = "Pike" },
                new County { Id = 115, CountyName = "Polk" },
                new County { Id = 116, CountyName = "Pulaski" },
                new County { Id = 117, CountyName = "Putnam" },
                new County { Id = 118, CountyName = "Quitman" },
                new County { Id = 119, CountyName = "Rabun" },
                new County { Id = 120, CountyName = "Randolph" },
                new County { Id = 121, CountyName = "Richmond" },
                new County { Id = 122, CountyName = "Rockdale" },
                new County { Id = 123, CountyName = "Schley" },
                new County { Id = 124, CountyName = "Screven" },
                new County { Id = 125, CountyName = "Seminole" },
                new County { Id = 126, CountyName = "Spalding" },
                new County { Id = 127, CountyName = "Stephens" },
                new County { Id = 128, CountyName = "Stewart" },
                new County { Id = 129, CountyName = "Sumter" },
                new County { Id = 130, CountyName = "Talbot" },
                new County { Id = 131, CountyName = "Taliaferro" },
                new County { Id = 132, CountyName = "Tattnall" },
                new County { Id = 133, CountyName = "Taylor" },
                new County { Id = 134, CountyName = "Telfair" },
                new County { Id = 135, CountyName = "Terrell" },
                new County { Id = 136, CountyName = "Thomas" },
                new County { Id = 137, CountyName = "Tift" },
                new County { Id = 138, CountyName = "Toombs" },
                new County { Id = 139, CountyName = "Towns" },
                new County { Id = 140, CountyName = "Treutlen" },
                new County { Id = 141, CountyName = "Troup" },
                new County { Id = 142, CountyName = "Turner" },
                new County { Id = 143, CountyName = "Twiggs" },
                new County { Id = 144, CountyName = "Union" },
                new County { Id = 145, CountyName = "Upson" },
                new County { Id = 146, CountyName = "Walker" },
                new County { Id = 147, CountyName = "Walton" },
                new County { Id = 148, CountyName = "Ware" },
                new County { Id = 149, CountyName = "Warren" },
                new County { Id = 150, CountyName = "Washington" },
                new County { Id = 151, CountyName = "Wayne" },
                new County { Id = 152, CountyName = "Webster" },
                new County { Id = 153, CountyName = "Wheeler" },
                new County { Id = 154, CountyName = "White" },
                new County { Id = 155, CountyName = "Whitfield" },
                new County { Id = 156, CountyName = "Wilcox" },
                new County { Id = 157, CountyName = "Wilkes" },
                new County { Id = 158, CountyName = "Wilkinson" },
                new County { Id = 159, CountyName = "Worth" }
            };

            return counties.ToArray();
        }
    }
}
