name: .NET Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install Playwright
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install supported browsers
        run: playwright install

      - name: Run the web server
        run: |
          cd src/Enfo.WebApp
          dotnet run &

      - name: Test
        run: dotnet test -- no-build verbosity normal PlayWright.ContextOptions.ignoreHTTPSErrors=true
